### ISSUE TITLE
static functions の欠落

### ISSUE THREAD

**Issue by uneco** [aoitaku/cocos2d-chipmunk-typescript-definitons#2]
`cp.momentForCircle` あたりがごっそり抜けてました……
案外素直な命名しててヘッダから定義吸い出せたので、型の対応取るやつだけお願いします！

吸い出すやつ（README.md に吸い出した結果があります）
https://github.com/uneco/chipmunk_static_functions_generator

**Comment by aoitaku** [comment]
oh.
**やり**
**ます**

**Comment by aoitaku** [comment]
```
areaForCircle (r1: cpFloat, r2: cpFloat): cpFloat
areaForSegment (a: cpVect, b: cpVect, radius: cpFloat): cpFloat
```
たぶんこれも

**Comment by uneco** [comment]
たぶん全部呼べるので、全部生えててもいいかなーって思います

**Comment by uneco** [comment]
(メソッド化されてるやつも含めて)

**Comment by aoitaku** [comment]
bBxx 気持ち悪いけどいちおうぜんぶやっときますか

**Comment by uneco** [comment]
bB 気持ち悪いけど仕方なさみある
